# Generated by Django 4.1 on 2022-11-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaNacimiento', models.DateField()),
                ('fono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1)),
                ('estado', models.IntegerField(choices=[(1, 'Vigente'), (2, 'Suspendido'), (3, 'Retirado')], default=1)),
            ],
        ),
    ]
