# Generated by Django 4.1 on 2022-11-22 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('Audifonos', 'Audifonos'), ('Mouse', 'Mouse'), ('Perifericos', 'Perifericos'), ('Consola', 'Consola'), ('Hardware', 'Hardware')], default='Audifonos', max_length=20)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre_encargado', models.CharField(max_length=30)),
                ('bodega_origen', models.CharField(choices=[('Temuco', 'Temuco'), ('Valdivia', 'Valdivia'), ('Villarrica', 'Villarrica'), ('Santiago', 'Santiago'), ('Valparaiso', 'Valparaiso')], default='Temuco', max_length=20)),
                ('bodega_destino', models.CharField(choices=[('Temuco', 'Temuco'), ('Valdivia', 'Valdivia'), ('Villarrica', 'Villarrica'), ('Santiago', 'Santiago'), ('Valparaiso', 'Valparaiso')], default='Temuco', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega_App.producto')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['nombre_encargado'],
            },
        ),
    ]
