# Generated by Django 4.1 on 2022-11-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_App', '0003_alter_movimiento_bodega_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='bodega_destino',
            field=models.CharField(choices=[('Temuco', 'Temuco'), ('Valdivia', 'Valdivia'), ('Villarrica', 'Villarrica'), ('Santiago', 'Santiago'), ('Valparaiso', 'Valparaiso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='bodega_origen',
            field=models.CharField(choices=[('Temuco', 'Temuco'), ('Valdivia', 'Valdivia'), ('Villarrica', 'Villarrica'), ('Santiago', 'Santiago'), ('Valparaiso', 'Valparaiso')], max_length=50),
        ),
    ]
