# Generated by Django 4.1 on 2022-09-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedido_App', '0004_asd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asd',
        ),
    ]
